//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Breaker.Wp7.Xna4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es_ES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Breaker.Wp7.Xna4.Resources.es-ES", typeof(es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de Breaker.
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisión de Breaker.
        /// </summary>
        internal static string AboutMenuItemReview {
            get {
                return ResourceManager.GetString("AboutMenuItemReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed &amp; Designed by#Anton Young &quot;Amsterdam&quot; The Netherlands#Senior Developer @Macaw Nederland B.V##Music Composed by#Stef de Wit &quot;Zaanstad&quot; The Netherlands####Translated by##Jaime Garcia-Figueruelo &quot;Spanish&quot;#Jospeh Maria-Oretga &quot;Portugeuse&quot;#Jana Stara &quot;Czech&quot;#Anton Young &quot;Dutch&quot;#Danial Kearney &quot;Irish&quot;#Anton Young &quot;English&quot;#Jenny Young-Hollingworth &quot;French&quot;###History:##Radarsoft in 1987 developed a similiar game#named also Breaker for the MSX 2 home computer.###                              Anton Young 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutMenuText {
            get {
                return ResourceManager.GetString("AboutMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucos de Breaker.
        /// </summary>
        internal static string CheatsMenu {
            get {
                return ResourceManager.GetString("CheatsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truco: comenzar como jugador doble.
        /// </summary>
        internal static string CheatsMenuItemDoublePlayer {
            get {
                return ResourceManager.GetString("CheatsMenuItemDoublePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Bloqueado.
        /// </summary>
        internal static string CheatsMenuItemLocked {
            get {
                return ResourceManager.GetString("CheatsMenuItemLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN.
        /// </summary>
        internal static string GameOverMenu {
            get {
                return ResourceManager.GetString("GameOverMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reintentar.
        /// </summary>
        internal static string GameOverMenuItemRetry {
            get {
                return ResourceManager.GetString("GameOverMenuItemRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BolaEX:.
        /// </summary>
        internal static string InformationExtraBall {
            get {
                return ResourceManager.GetString("InformationExtraBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIVEL:{0:00}.
        /// </summary>
        internal static string InformationLevel {
            get {
                return ResourceManager.GetString("InformationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOLAS:{0:00}.
        /// </summary>
        internal static string InformationLives {
            get {
                return ResourceManager.GetString("InformationLives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUNTOS:{0:00000000}.
        /// </summary>
        internal static string InformationPoints {
            get {
                return ResourceManager.GetString("InformationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando ....
        /// </summary>
        internal static string LoadLoading {
            get {
                return ResourceManager.GetString("LoadLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú de Breaker.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de.
        /// </summary>
        internal static string MainMenuItemAbout {
            get {
                return ResourceManager.GetString("MainMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Juego.
        /// </summary>
        internal static string MainMenuItemGame {
            get {
                return ResourceManager.GetString("MainMenuItemGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        internal static string MainMenuItemOptions {
            get {
                return ResourceManager.GetString("MainMenuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        internal static string MenuItemBack {
            get {
                return ResourceManager.GetString("MenuItemBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones de Breaker.
        /// </summary>
        internal static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trucos.
        /// </summary>
        internal static string OptionsMenuItemCheats {
            get {
                return ResourceManager.GetString("OptionsMenuItemCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string OptionsMenuItemSettings {
            get {
                return ResourceManager.GetString("OptionsMenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trofeos.
        /// </summary>
        internal static string OptionsMenuItemTrophies {
            get {
                return ResourceManager.GetString("OptionsMenuItemTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausa Menú.
        /// </summary>
        internal static string PauseMenu {
            get {
                return ResourceManager.GetString("PauseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        internal static string PauseMenuItemContinue {
            get {
                return ResourceManager.GetString("PauseMenuItemContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string PauseMenuItemSettings {
            get {
                return ResourceManager.GetString("PauseMenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holandés,Español,Inglés.
        /// </summary>
        internal static string SettingsLanguages {
            get {
                return ResourceManager.GetString("SettingsLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de Breaker.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosidad.
        /// </summary>
        internal static string SettingsMenuItemBrightness {
            get {
                return ResourceManager.GetString("SettingsMenuItemBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string SettingsMenuItemLanguages {
            get {
                return ResourceManager.GetString("SettingsMenuItemLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumen.
        /// </summary>
        internal static string SettingsMenuItemVolume {
            get {
                return ResourceManager.GetString("SettingsMenuItemVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rompe 10.000 veces ladrillos de 20 puntos.
        /// </summary>
        internal static string TrophieDescription20Points {
            get {
                return ResourceManager.GetString("TrophieDescription20Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rompe 10.000 veces ladrillos de 30 puntos.
        /// </summary>
        internal static string TrophieDescription30Points {
            get {
                return ResourceManager.GetString("TrophieDescription30Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completar todos los niveles.
        /// </summary>
        internal static string TrophieDescriptionAllCompleted {
            get {
                return ResourceManager.GetString("TrophieDescriptionAllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perder una bola cuando rompes una flecha.
        /// </summary>
        internal static string TrophieDescriptionArrows {
            get {
                return ResourceManager.GetString("TrophieDescriptionArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleccionar 10.000 bonus.
        /// </summary>
        internal static string TrophieDescriptionBonusCollector {
            get {
                return ResourceManager.GetString("TrophieDescriptionBonusCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romper un ladrillo.
        /// </summary>
        internal static string TrophieDescriptionBrokeIt {
            get {
                return ResourceManager.GetString("TrophieDescriptionBrokeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completa un nivel sin perder una bola.
        /// </summary>
        internal static string TrophieDescriptionCareful {
            get {
                return ResourceManager.GetString("TrophieDescriptionCareful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usar los túneles al menos 1.000 veces.
        /// </summary>
        internal static string TrophieDescriptionDark {
            get {
                return ResourceManager.GetString("TrophieDescriptionDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activar 1.000 veces el segundo jugador.
        /// </summary>
        internal static string TrophieDescriptionEasy {
            get {
                return ResourceManager.GetString("TrophieDescriptionEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer nivel completo.
        /// </summary>
        internal static string TrophieDescriptionFirstLevel {
            get {
                return ResourceManager.GetString("TrophieDescriptionFirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasa por el túnel.
        /// </summary>
        internal static string TrophieDescriptionGettingDark {
            get {
                return ResourceManager.GetString("TrophieDescriptionGettingDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rompe hasta que hayas desbloqueado este trofeo.
        /// </summary>
        internal static string TrophieDescriptionHidden {
            get {
                return ResourceManager.GetString("TrophieDescriptionHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rompe 10.000 veces ladrillos de 40 puntos.
        /// </summary>
        internal static string TrophieDescriptionHighPoints {
            get {
                return ResourceManager.GetString("TrophieDescriptionHighPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gana 100.000 o más puntos.
        /// </summary>
        internal static string TrophieDescriptionHighScore {
            get {
                return ResourceManager.GetString("TrophieDescriptionHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo completar el nivel.
        /// </summary>
        internal static string TrophieDescriptionHopeless {
            get {
                return ResourceManager.GetString("TrophieDescriptionHopeless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleccionar 1.000 bolas extra.
        /// </summary>
        internal static string TrophieDescriptionLoose {
            get {
                return ResourceManager.GetString("TrophieDescriptionLoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gana 10.000 o más puntos.
        /// </summary>
        internal static string TrophieDescriptionLowScore {
            get {
                return ResourceManager.GetString("TrophieDescriptionLowScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rompe un millón de ladrillos.
        /// </summary>
        internal static string TrophieDescriptionNowBreaking {
            get {
                return ResourceManager.GetString("TrophieDescriptionNowBreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear todos los trofeos.
        /// </summary>
        internal static string TrophieDescriptionPlatinum {
            get {
                return ResourceManager.GetString("TrophieDescriptionPlatinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perder el segundo jugador 1.000 veces.
        /// </summary>
        internal static string TrophieDescriptionScared {
            get {
                return ResourceManager.GetString("TrophieDescriptionScared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gana un millón de puntos o más.
        /// </summary>
        internal static string TrophieDescriptionWonMillion {
            get {
                return ResourceManager.GetString("TrophieDescriptionWonMillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trofeos de Breaker.
        /// </summary>
        internal static string TrophiesMenu {
            get {
                return ResourceManager.GetString("TrophiesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaker de 20 Puntos.
        /// </summary>
        internal static string TrophieTitle20Points {
            get {
                return ResourceManager.GetString("TrophieTitle20Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaker de 30 Puntos.
        /// </summary>
        internal static string TrophieTitle30Points {
            get {
                return ResourceManager.GetString("TrophieTitle30Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los Niveles Completos.
        /// </summary>
        internal static string TrophieTitleAllCompleted {
            get {
                return ResourceManager.GetString("TrophieTitleAllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No me gustan las Flechas.
        /// </summary>
        internal static string TrophieTitleArrows {
            get {
                return ResourceManager.GetString("TrophieTitleArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colector de Bonus.
        /// </summary>
        internal static string TrophieTitleBonusCollector {
            get {
                return ResourceManager.GetString("TrophieTitleBonusCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo Rompiste.
        /// </summary>
        internal static string TrophieTitleBrokeIt {
            get {
                return ResourceManager.GetString("TrophieTitleBrokeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuidado.
        /// </summary>
        internal static string TrophieTitleCareful {
            get {
                return ResourceManager.GetString("TrophieTitleCareful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me gusta la Oscuridad.
        /// </summary>
        internal static string TrophieTitleDark {
            get {
                return ResourceManager.GetString("TrophieTitleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranquilo.
        /// </summary>
        internal static string TrophieTitleEasy {
            get {
                return ResourceManager.GetString("TrophieTitleEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu primer Nivel.
        /// </summary>
        internal static string TrophieTitleFirstLevel {
            get {
                return ResourceManager.GetString("TrophieTitleFirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está Oscureciendo.
        /// </summary>
        internal static string TrophieTitleGettingDark {
            get {
                return ResourceManager.GetString("TrophieTitleGettingDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trofeo Escondido.
        /// </summary>
        internal static string TrophieTitleHidden {
            get {
                return ResourceManager.GetString("TrophieTitleHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos Alta.
        /// </summary>
        internal static string TrophieTitleHighPoints {
            get {
                return ResourceManager.GetString("TrophieTitleHighPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntuación Alta.
        /// </summary>
        internal static string TrophieTitleHighScore {
            get {
                return ResourceManager.GetString("TrophieTitleHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soy Malísimo Rompiendo Cosas.
        /// </summary>
        internal static string TrophieTitleHopeless {
            get {
                return ResourceManager.GetString("TrophieTitleHopeless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No me gusta Perder.
        /// </summary>
        internal static string TrophieTitleLoose {
            get {
                return ResourceManager.GetString("TrophieTitleLoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntuación Baja.
        /// </summary>
        internal static string TrophieTitleLowScore {
            get {
                return ResourceManager.GetString("TrophieTitleLowScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahora sí que estás Rompiendo.
        /// </summary>
        internal static string TrophieTitleNowBreaking {
            get {
                return ResourceManager.GetString("TrophieTitleNowBreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campeón Trophie de Breaker.
        /// </summary>
        internal static string TrophieTitlePlatinum {
            get {
                return ResourceManager.GetString("TrophieTitlePlatinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tengo Miedo.
        /// </summary>
        internal static string TrophieTitleScared {
            get {
                return ResourceManager.GetString("TrophieTitleScared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gana un Millón.
        /// </summary>
        internal static string TrophieTitleWonMillion {
            get {
                return ResourceManager.GetString("TrophieTitleWonMillion", resourceCulture);
            }
        }
    }
}
