//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Breaker.Wp7.Xna4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class nl_NL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal nl_NL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Breaker.Wp7.Xna4.Resources.nl-NL", typeof(nl_NL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Breaker.
        /// </summary>
        internal static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recentie Breaker.
        /// </summary>
        internal static string AboutMenuItemReview {
            get {
                return ResourceManager.GetString("AboutMenuItemReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed &amp; Designed by#Anton Young &quot;Amsterdam&quot; The Netherlands#Senior Developer @Macaw Nederland B.V##Music Composed by#Stef de Wit &quot;Zaanstad&quot; The Netherlands####Translated by##Jaime Garcia-Figueruelo &quot;Spanish&quot;#Jospeh Maria-Oretga &quot;Portugeuse&quot;#Jana Stara &quot;Czech&quot;#Anton Young &quot;Dutch&quot;#Danial Kearney &quot;Irish&quot;#Anton Young &quot;English&quot;#Jenny Young-Hollingworth &quot;French&quot;###History:##Radarsoft in 1987 developed a similiar game#named also Breaker for the MSX 2 home computer.###                              Anton Young 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutMenuText {
            get {
                return ResourceManager.GetString("AboutMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaker Valsspelen.
        /// </summary>
        internal static string CheatsMenu {
            get {
                return ResourceManager.GetString("CheatsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheat: Start met 2 spelers.
        /// </summary>
        internal static string CheatsMenuItemDoublePlayer {
            get {
                return ResourceManager.GetString("CheatsMenuItemDoublePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Vergrendeld.
        /// </summary>
        internal static string CheatsMenuItemLocked {
            get {
                return ResourceManager.GetString("CheatsMenuItemLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EINDE SPEL.
        /// </summary>
        internal static string GameOverMenu {
            get {
                return ResourceManager.GetString("GameOverMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opnieuw.
        /// </summary>
        internal static string GameOverMenuItemRetry {
            get {
                return ResourceManager.GetString("GameOverMenuItemRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XBal:.
        /// </summary>
        internal static string InformationExtraBall {
            get {
                return ResourceManager.GetString("InformationExtraBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIVEAU:{0:00}.
        /// </summary>
        internal static string InformationLevel {
            get {
                return ResourceManager.GetString("InformationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAL:{0:00}.
        /// </summary>
        internal static string InformationLives {
            get {
                return ResourceManager.GetString("InformationLives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCORE:{0:0000000}.
        /// </summary>
        internal static string InformationPoints {
            get {
                return ResourceManager.GetString("InformationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aan het laden....
        /// </summary>
        internal static string LoadLoading {
            get {
                return ResourceManager.GetString("LoadLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaker Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Beaker.
        /// </summary>
        internal static string MainMenuItemAbout {
            get {
                return ResourceManager.GetString("MainMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw Spel.
        /// </summary>
        internal static string MainMenuItemGame {
            get {
                return ResourceManager.GetString("MainMenuItemGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opties.
        /// </summary>
        internal static string MainMenuItemOptions {
            get {
                return ResourceManager.GetString("MainMenuItemOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug.
        /// </summary>
        internal static string MenuItemBack {
            get {
                return ResourceManager.GetString("MenuItemBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluiten.
        /// </summary>
        internal static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opties Menu.
        /// </summary>
        internal static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valsspelen.
        /// </summary>
        internal static string OptionsMenuItemCheats {
            get {
                return ResourceManager.GetString("OptionsMenuItemCheats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string OptionsMenuItemSettings {
            get {
                return ResourceManager.GetString("OptionsMenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trofeeën.
        /// </summary>
        internal static string OptionsMenuItemTrophies {
            get {
                return ResourceManager.GetString("OptionsMenuItemTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauze Menu.
        /// </summary>
        internal static string PauseMenu {
            get {
                return ResourceManager.GetString("PauseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doorgaan.
        /// </summary>
        internal static string PauseMenuItemContinue {
            get {
                return ResourceManager.GetString("PauseMenuItemContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string PauseMenuItemSettings {
            get {
                return ResourceManager.GetString("PauseMenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands,Spaans,Engels.
        /// </summary>
        internal static string SettingsLanguages {
            get {
                return ResourceManager.GetString("SettingsLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen Menu.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helderheid.
        /// </summary>
        internal static string SettingsMenuItemBrightness {
            get {
                return ResourceManager.GetString("SettingsMenuItemBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        internal static string SettingsMenuItemLanguages {
            get {
                return ResourceManager.GetString("SettingsMenuItemLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string SettingsMenuItemVolume {
            get {
                return ResourceManager.GetString("SettingsMenuItemVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breek 10.000 maal de 20 punten breekbaar.
        /// </summary>
        internal static string TrophieDescription20Points {
            get {
                return ResourceManager.GetString("TrophieDescription20Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breek 10.000 maal de 30 punten breekbaar.
        /// </summary>
        internal static string TrophieDescription30Points {
            get {
                return ResourceManager.GetString("TrophieDescription30Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltooi alle niveaus in het Spel.
        /// </summary>
        internal static string TrophieDescriptionAllCompleted {
            get {
                return ResourceManager.GetString("TrophieDescriptionAllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlies jouw Bal terwijl je een pijl gebroken hebt.
        /// </summary>
        internal static string TrophieDescriptionArrows {
            get {
                return ResourceManager.GetString("TrophieDescriptionArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzamel 10.000 Bonus.
        /// </summary>
        internal static string TrophieDescriptionBonusCollector {
            get {
                return ResourceManager.GetString("TrophieDescriptionBonusCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breek een breekbaar.
        /// </summary>
        internal static string TrophieDescriptionBrokeIt {
            get {
                return ResourceManager.GetString("TrophieDescriptionBrokeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltooi een niveau zonder een bal te verliezen.
        /// </summary>
        internal static string TrophieDescriptionCareful {
            get {
                return ResourceManager.GetString("TrophieDescriptionCareful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik de tunnels tenminste 1000 keer.
        /// </summary>
        internal static string TrophieDescriptionDark {
            get {
                return ResourceManager.GetString("TrophieDescriptionDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activeer de tweede speler 1000 keer.
        /// </summary>
        internal static string TrophieDescriptionEasy {
            get {
                return ResourceManager.GetString("TrophieDescriptionEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltooi de 1st niveau.
        /// </summary>
        internal static string TrophieDescriptionFirstLevel {
            get {
                return ResourceManager.GetString("TrophieDescriptionFirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ga door een Tunnel.
        /// </summary>
        internal static string TrophieDescriptionGettingDark {
            get {
                return ResourceManager.GetString("TrophieDescriptionGettingDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breek totdat je deze Trophee ontgrendeld hebt.
        /// </summary>
        internal static string TrophieDescriptionHidden {
            get {
                return ResourceManager.GetString("TrophieDescriptionHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breek 10.000 maal de 40 punten breekbaar.
        /// </summary>
        internal static string TrophieDescriptionHighPoints {
            get {
                return ResourceManager.GetString("TrophieDescriptionHighPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdien 100.000 punten of meer.
        /// </summary>
        internal static string TrophieDescriptionHighScore {
            get {
                return ResourceManager.GetString("TrophieDescriptionHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faal de eerste niveau.
        /// </summary>
        internal static string TrophieDescriptionHopeless {
            get {
                return ResourceManager.GetString("TrophieDescriptionHopeless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzamel 1000 keer een extra bal.
        /// </summary>
        internal static string TrophieDescriptionLoose {
            get {
                return ResourceManager.GetString("TrophieDescriptionLoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdien 10.000 punten of meer.
        /// </summary>
        internal static string TrophieDescriptionLowScore {
            get {
                return ResourceManager.GetString("TrophieDescriptionLowScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breek een miljoen breekbaars.
        /// </summary>
        internal static string TrophieDescriptionNowBreaking {
            get {
                return ResourceManager.GetString("TrophieDescriptionNowBreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontgrendel elk Trophee in Breaker.
        /// </summary>
        internal static string TrophieDescriptionPlatinum {
            get {
                return ResourceManager.GetString("TrophieDescriptionPlatinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verlies 1.000 keer je tweede speler.
        /// </summary>
        internal static string TrophieDescriptionScared {
            get {
                return ResourceManager.GetString("TrophieDescriptionScared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdien een miljoen punten of meer.
        /// </summary>
        internal static string TrophieDescriptionWonMillion {
            get {
                return ResourceManager.GetString("TrophieDescriptionWonMillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaker Tropheeën.
        /// </summary>
        internal static string TrophiesMenu {
            get {
                return ResourceManager.GetString("TrophiesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 Punten Breeker.
        /// </summary>
        internal static string TrophieTitle20Points {
            get {
                return ResourceManager.GetString("TrophieTitle20Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Punten Breeker.
        /// </summary>
        internal static string TrophieTitle30Points {
            get {
                return ResourceManager.GetString("TrophieTitle30Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behaal alle Niveaus.
        /// </summary>
        internal static string TrophieTitleAllCompleted {
            get {
                return ResourceManager.GetString("TrophieTitleAllCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik hou niet van Pijlen.
        /// </summary>
        internal static string TrophieTitleArrows {
            get {
                return ResourceManager.GetString("TrophieTitleArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Verzamelaar.
        /// </summary>
        internal static string TrophieTitleBonusCollector {
            get {
                return ResourceManager.GetString("TrophieTitleBonusCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt het gebroken.
        /// </summary>
        internal static string TrophieTitleBrokeIt {
            get {
                return ResourceManager.GetString("TrophieTitleBrokeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wees Voorzichtig.
        /// </summary>
        internal static string TrophieTitleCareful {
            get {
                return ResourceManager.GetString("TrophieTitleCareful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik Hou van om in het Donker te Zijn.
        /// </summary>
        internal static string TrophieTitleDark {
            get {
                return ResourceManager.GetString("TrophieTitleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doe het Makkelijk.
        /// </summary>
        internal static string TrophieTitleEasy {
            get {
                return ResourceManager.GetString("TrophieTitleEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouw Eerste Niveau.
        /// </summary>
        internal static string TrophieTitleFirstLevel {
            get {
                return ResourceManager.GetString("TrophieTitleFirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wordt Donker hier.
        /// </summary>
        internal static string TrophieTitleGettingDark {
            get {
                return ResourceManager.GetString("TrophieTitleGettingDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verborgen Trophee.
        /// </summary>
        internal static string TrophieTitleHidden {
            get {
                return ResourceManager.GetString("TrophieTitleHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoge Punten Breaker.
        /// </summary>
        internal static string TrophieTitleHighPoints {
            get {
                return ResourceManager.GetString("TrophieTitleHighPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoge Score.
        /// </summary>
        internal static string TrophieTitleHighScore {
            get {
                return ResourceManager.GetString("TrophieTitleHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ben Waardeloos in dingen Kapot te maken.
        /// </summary>
        internal static string TrophieTitleHopeless {
            get {
                return ResourceManager.GetString("TrophieTitleHopeless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik Hou niet van om te Verliezen.
        /// </summary>
        internal static string TrophieTitleLoose {
            get {
                return ResourceManager.GetString("TrophieTitleLoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lage Score.
        /// </summary>
        internal static string TrophieTitleLowScore {
            get {
                return ResourceManager.GetString("TrophieTitleLowScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu ben je aan het Breken.
        /// </summary>
        internal static string TrophieTitleNowBreaking {
            get {
                return ResourceManager.GetString("TrophieTitleNowBreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaker Trophee Kampioen.
        /// </summary>
        internal static string TrophieTitlePlatinum {
            get {
                return ResourceManager.GetString("TrophieTitlePlatinum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ben niet Bang.
        /// </summary>
        internal static string TrophieTitleScared {
            get {
                return ResourceManager.GetString("TrophieTitleScared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win een Miljoen.
        /// </summary>
        internal static string TrophieTitleWonMillion {
            get {
                return ResourceManager.GetString("TrophieTitleWonMillion", resourceCulture);
            }
        }
    }
}
